apiVersion: v1
kind: Service
metadata:
  name: engine-fnns-consumer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: 호스트 네임
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 쿠버네티스
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  selector:
    app: engine-fnns-consumer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
  type: LoadBalancer